// seed.js
// Run this ONCE from inside your backend/ folder to populate MongoDB Atlas
// Usage: node seed.js
//
// Make sure:
// 1. This file sits in backend/ (same level as server.js)
// 2. backend/.env has MONGO_URI set
// 3. backend/models/Place.js already exists

import dotenv from "dotenv";
dotenv.config();
import mongoose from "mongoose";
import Place from "./models/Place.js";
const places = [
  // ---------------- KARNATAKA ----------------
  {
    name: "Mysore Palace",
    state: "Karnataka",
    city: "Mysore",
    image: "",
    description: "Historic royal palace of the Wadiyar dynasty, famous for its Indo-Saracenic architecture and dazzling illumination during Dasara.",
    bestTime: "October - February",
    entryFee: 70,
    rating: 4.7,
    location: "Mysore, Karnataka",
  },
  {
    name: "Hampi",
    state: "Karnataka",
    city: "Hampi",
    image: "",
    description: "UNESCO World Heritage site with ruins of the Vijayanagara Empire, boulder landscapes, and ancient temples.",
    bestTime: "October - February",
    entryFee: 40,
    rating: 4.8,
    location: "Hampi, Karnataka",
  },
  {
    name: "Coorg",
    state: "Karnataka",
    city: "Madikeri",
    image: "",
    description: "Misty hill station known as the 'Scotland of India', famous for coffee plantations and lush greenery.",
    bestTime: "October - March",
    entryFee: 0,
    rating: 4.6,
    location: "Madikeri, Karnataka",
  },
  {
    name: "Jog Falls",
    state: "Karnataka",
    city: "Shimoga",
    image: "",
    description: "One of India's highest waterfalls, formed by the Sharavathi river plunging dramatically into a gorge.",
    bestTime: "July - September",
    entryFee: 15,
    rating: 4.5,
    location: "Shimoga, Karnataka",
  },
  {
    name: "Nandi Hills",
    state: "Karnataka",
    city: "Chikkaballapur",
    image: "",
    description: "Popular hill station near Bengaluru known for stunning sunrise views and ancient fort ruins.",
    bestTime: "September - February",
    entryFee: 30,
    rating: 4.3,
    location: "Chikkaballapur, Karnataka",
  },

  // ---------------- KERALA ----------------
  {
    name: "Munnar",
    state: "Kerala",
    city: "Idukki",
    image: "",
    description: "Hill station carpeted with rolling tea plantations, misty peaks, and cool mountain air.",
    bestTime: "September - March",
    entryFee: 0,
    rating: 4.8,
    location: "Munnar, Kerala",
  },
  {
    name: "Alleppey Backwaters",
    state: "Kerala",
    city: "Alappuzha",
    image: "",
    description: "Serene network of canals, lagoons, and lakes, best experienced aboard a traditional houseboat.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.7,
    location: "Alappuzha, Kerala",
  },
  {
    name: "Wayanad",
    state: "Kerala",
    city: "Wayanad",
    image: "",
    description: "Green district with wildlife sanctuaries, spice plantations, and ancient caves.",
    bestTime: "October - May",
    entryFee: 20,
    rating: 4.6,
    location: "Wayanad, Kerala",
  },
  {
    name: "Kovalam Beach",
    state: "Kerala",
    city: "Thiruvananthapuram",
    image: "",
    description: "Crescent-shaped beach with a famous lighthouse, popular for its calm waters and Ayurvedic resorts.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.4,
    location: "Thiruvananthapuram, Kerala",
  },
  {
    name: "Athirappilly Falls",
    state: "Kerala",
    city: "Thrissur",
    image: "",
    description: "Kerala's largest waterfall, often called the 'Niagara of India', surrounded by dense forest.",
    bestTime: "June - January",
    entryFee: 40,
    rating: 4.5,
    location: "Thrissur, Kerala",
  },

  // ---------------- TAMIL NADU ----------------
  {
    name: "Meenakshi Temple",
    state: "Tamil Nadu",
    city: "Madurai",
    image: "",
    description: "Iconic temple complex dedicated to Goddess Meenakshi, renowned for its towering, sculpted gopurams.",
    bestTime: "October - March",
    entryFee: 0,
    rating: 4.8,
    location: "Madurai, Tamil Nadu",
  },
  {
    name: "Ooty",
    state: "Tamil Nadu",
    city: "Nilgiris",
    image: "",
    description: "Queen of the Nilgiris, a colonial-era hill station with botanical gardens and a toy train.",
    bestTime: "October - June",
    entryFee: 0,
    rating: 4.5,
    location: "Ooty, Tamil Nadu",
  },
  {
    name: "Mahabalipuram",
    state: "Tamil Nadu",
    city: "Chengalpattu",
    image: "",
    description: "UNESCO World Heritage site famous for its ancient rock-cut temples and Shore Temple by the sea.",
    bestTime: "November - February",
    entryFee: 40,
    rating: 4.6,
    location: "Mahabalipuram, Tamil Nadu",
  },
  {
    name: "Kodaikanal",
    state: "Tamil Nadu",
    city: "Dindigul",
    image: "",
    description: "Picturesque hill station known as the 'Princess of Hill Stations', built around a star-shaped lake.",
    bestTime: "September - May",
    entryFee: 0,
    rating: 4.6,
    location: "Kodaikanal, Tamil Nadu",
  },
  {
    name: "Marina Beach",
    state: "Tamil Nadu",
    city: "Chennai",
    image: "",
    description: "One of the longest urban beaches in the world, a lively promenade along the Bay of Bengal.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.2,
    location: "Chennai, Tamil Nadu",
  },

  // ---------------- GOA ----------------
  {
    name: "Baga Beach",
    state: "Goa",
    city: "North Goa",
    image: "",
    description: "Lively beach known for water sports, beach shacks, and vibrant nightlife.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.4,
    location: "North Goa, Goa",
  },
  {
    name: "Basilica of Bom Jesus",
    state: "Goa",
    city: "Old Goa",
    image: "",
    description: "UNESCO World Heritage baroque church holding the mortal remains of St. Francis Xavier.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.7,
    location: "Old Goa, Goa",
  },
  {
    name: "Dudhsagar Falls",
    state: "Goa",
    city: "South Goa",
    image: "",
    description: "Four-tiered waterfall on the Mandovi river, one of India's tallest, set inside a wildlife sanctuary.",
    bestTime: "June - September",
    entryFee: 50,
    rating: 4.6,
    location: "South Goa, Goa",
  },
  {
    name: "Fort Aguada",
    state: "Goa",
    city: "North Goa",
    image: "",
    description: "17th-century Portuguese fort overlooking the Arabian Sea, with a well-preserved lighthouse.",
    bestTime: "November - February",
    entryFee: 25,
    rating: 4.4,
    location: "North Goa, Goa",
  },
  {
    name: "Anjuna Beach",
    state: "Goa",
    city: "North Goa",
    image: "",
    description: "Bohemian beach famous for its Wednesday flea market and laid-back café culture.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.3,
    location: "North Goa, Goa",
  },

  // ---------------- MAHARASHTRA ----------------
  {
    name: "Gateway of India",
    state: "Maharashtra",
    city: "Mumbai",
    image: "",
    description: "Iconic 20th-century arch monument overlooking the Arabian Sea, built to commemorate King George V's visit.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.5,
    location: "Mumbai, Maharashtra",
  },
  {
    name: "Ajanta Caves",
    state: "Maharashtra",
    city: "Aurangabad",
    image: "",
    description: "UNESCO World Heritage rock-cut Buddhist cave monuments dating back over 2,000 years, with intricate murals.",
    bestTime: "November - March",
    entryFee: 40,
    rating: 4.7,
    location: "Aurangabad, Maharashtra",
  },
  {
    name: "Ellora Caves",
    state: "Maharashtra",
    city: "Aurangabad",
    image: "",
    description: "UNESCO World Heritage site with 34 rock-cut monasteries and temples representing Buddhism, Hinduism, and Jainism.",
    bestTime: "November - March",
    entryFee: 40,
    rating: 4.7,
    location: "Aurangabad, Maharashtra",
  },
  {
    name: "Lonavala",
    state: "Maharashtra",
    city: "Pune",
    image: "",
    description: "Popular hill station between Mumbai and Pune known for its monsoon waterfalls and viewpoints.",
    bestTime: "June - September",
    entryFee: 0,
    rating: 4.3,
    location: "Pune, Maharashtra",
  },
  {
    name: "Shirdi",
    state: "Maharashtra",
    city: "Ahmednagar",
    image: "",
    description: "Major pilgrimage town centered around the Sai Baba Temple, visited by millions each year.",
    bestTime: "October - March",
    entryFee: 0,
    rating: 4.6,
    location: "Ahmednagar, Maharashtra",
  },

  // ---------------- RAJASTHAN ----------------
  {
    name: "Amber Fort",
    state: "Rajasthan",
    city: "Jaipur",
    image: "",
    description: "Majestic hilltop fort with mirrored halls and courtyards, overlooking Maota Lake.",
    bestTime: "October - March",
    entryFee: 100,
    rating: 4.8,
    location: "Jaipur, Rajasthan",
  },
  {
    name: "Hawa Mahal",
    state: "Rajasthan",
    city: "Jaipur",
    image: "",
    description: "Iconic five-story pink sandstone palace with 953 small windows, built for royal women to observe street life.",
    bestTime: "October - March",
    entryFee: 50,
    rating: 4.6,
    location: "Jaipur, Rajasthan",
  },
  {
    name: "Lake Pichola",
    state: "Rajasthan",
    city: "Udaipur",
    image: "",
    description: "Scenic artificial lake surrounded by palaces, ghats, and hills, best seen at sunset.",
    bestTime: "September - March",
    entryFee: 0,
    rating: 4.7,
    location: "Udaipur, Rajasthan",
  },
  {
    name: "Jaisalmer Fort",
    state: "Rajasthan",
    city: "Jaisalmer",
    image: "",
    description: "Living fort of golden sandstone rising from the Thar Desert, still home to thousands of residents.",
    bestTime: "October - February",
    entryFee: 50,
    rating: 4.7,
    location: "Jaisalmer, Rajasthan",
  },
  {
    name: "Mehrangarh Fort",
    state: "Rajasthan",
    city: "Jodhpur",
    image: "",
    description: "One of India's largest forts, perched on a rocky hill above the Blue City with sweeping desert views.",
    bestTime: "October - March",
    entryFee: 100,
    rating: 4.8,
    location: "Jodhpur, Rajasthan",
  },

  // ---------------- UTTAR PRADESH ----------------
  {
    name: "Taj Mahal",
    state: "Uttar Pradesh",
    city: "Agra",
    image: "",
    description: "UNESCO World Heritage ivory-white marble mausoleum, one of the New Seven Wonders of the World.",
    bestTime: "October - March",
    entryFee: 250,
    rating: 4.9,
    location: "Agra, Uttar Pradesh",
  },
  {
    name: "Agra Fort",
    state: "Uttar Pradesh",
    city: "Agra",
    image: "",
    description: "UNESCO World Heritage red sandstone fort that served as the main residence of Mughal emperors.",
    bestTime: "October - March",
    entryFee: 50,
    rating: 4.6,
    location: "Agra, Uttar Pradesh",
  },
  {
    name: "Varanasi Ghats",
    state: "Uttar Pradesh",
    city: "Varanasi",
    image: "",
    description: "Sacred riverfront steps along the Ganges, famous for the evening Ganga Aarti ceremony.",
    bestTime: "October - March",
    entryFee: 0,
    rating: 4.7,
    location: "Varanasi, Uttar Pradesh",
  },
  {
    name: "Fatehpur Sikri",
    state: "Uttar Pradesh",
    city: "Agra",
    image: "",
    description: "UNESCO World Heritage abandoned Mughal city built by Emperor Akbar, remarkably well preserved.",
    bestTime: "October - March",
    entryFee: 35,
    rating: 4.5,
    location: "Agra, Uttar Pradesh",
  },
  {
    name: "Sarnath",
    state: "Uttar Pradesh",
    city: "Varanasi",
    image: "",
    description: "Historic site where Buddha delivered his first sermon, home to ancient stupas and monasteries.",
    bestTime: "October - March",
    entryFee: 25,
    rating: 4.4,
    location: "Varanasi, Uttar Pradesh",
  },

  // ---------------- HIMACHAL PRADESH ----------------
  {
    name: "Shimla",
    state: "Himachal Pradesh",
    city: "Shimla",
    image: "",
    description: "Former British summer capital, known for colonial architecture, the Mall Road, and toy train.",
    bestTime: "March - June",
    entryFee: 0,
    rating: 4.5,
    location: "Shimla, Himachal Pradesh",
  },
  {
    name: "Manali",
    state: "Himachal Pradesh",
    city: "Kullu",
    image: "",
    description: "Popular hill town in the Kullu valley, gateway to adventure sports and Himalayan trekking.",
    bestTime: "October - June",
    entryFee: 0,
    rating: 4.7,
    location: "Kullu, Himachal Pradesh",
  },
  {
    name: "Dharamshala",
    state: "Himachal Pradesh",
    city: "Kangra",
    image: "",
    description: "Home to the Dalai Lama and Tibetan government-in-exile, set against snow-capped Dhauladhar peaks.",
    bestTime: "March - June",
    entryFee: 0,
    rating: 4.6,
    location: "Kangra, Himachal Pradesh",
  },
  {
    name: "Spiti Valley",
    state: "Himachal Pradesh",
    city: "Lahaul and Spiti",
    image: "",
    description: "Remote high-altitude cold desert valley with ancient monasteries and dramatic Himalayan landscapes.",
    bestTime: "May - October",
    entryFee: 0,
    rating: 4.8,
    location: "Lahaul and Spiti, Himachal Pradesh",
  },
  {
    name: "Kasol",
    state: "Himachal Pradesh",
    city: "Kullu",
    image: "",
    description: "Riverside village in the Parvati Valley, popular with backpackers for trekking and cafe culture.",
    bestTime: "March - June",
    entryFee: 0,
    rating: 4.5,
    location: "Kullu, Himachal Pradesh",
  },

  // ---------------- WEST BENGAL ----------------
  {
    name: "Victoria Memorial",
    state: "West Bengal",
    city: "Kolkata",
    image: "",
    description: "Grand white marble monument built in memory of Queen Victoria, now a museum and popular garden park.",
    bestTime: "October - March",
    entryFee: 30,
    rating: 4.6,
    location: "Kolkata, West Bengal",
  },
  {
    name: "Darjeeling",
    state: "West Bengal",
    city: "Darjeeling",
    image: "",
    description: "Hill station famous for its tea gardens, the toy train, and sweeping views of Kanchenjunga.",
    bestTime: "March - May",
    entryFee: 0,
    rating: 4.7,
    location: "Darjeeling, West Bengal",
  },
  {
    name: "Sundarbans",
    state: "West Bengal",
    city: "South 24 Parganas",
    image: "",
    description: "UNESCO World Heritage mangrove forest and tiger reserve, the largest of its kind in the world.",
    bestTime: "November - February",
    entryFee: 60,
    rating: 4.5,
    location: "South 24 Parganas, West Bengal",
  },
  {
    name: "Howrah Bridge",
    state: "West Bengal",
    city: "Kolkata",
    image: "",
    description: "Iconic cantilever bridge over the Hooghly River, one of the busiest bridges in the world.",
    bestTime: "October - March",
    entryFee: 0,
    rating: 4.4,
    location: "Kolkata, West Bengal",
  },
  {
    name: "Kalimpong",
    state: "West Bengal",
    city: "Kalimpong",
    image: "",
    description: "Quiet hill town known for its monasteries, nurseries, and views of the Teesta valley.",
    bestTime: "March - June",
    entryFee: 0,
    rating: 4.4,
    location: "Kalimpong, West Bengal",
  },

  // ---------------- GUJARAT ----------------
  {
    name: "Statue of Unity",
    state: "Gujarat",
    city: "Narmada",
    image: "",
    description: "World's tallest statue, honoring Sardar Vallabhbhai Patel, overlooking the Narmada Dam.",
    bestTime: "October - February",
    entryFee: 150,
    rating: 4.7,
    location: "Narmada, Gujarat",
  },
  {
    name: "Rann of Kutch",
    state: "Gujarat",
    city: "Kutch",
    image: "",
    description: "Vast white salt marsh that transforms into a moonlit desert festival ground during the Rann Utsav.",
    bestTime: "November - February",
    entryFee: 0,
    rating: 4.8,
    location: "Kutch, Gujarat",
  },
  {
    name: "Gir National Park",
    state: "Gujarat",
    city: "Junagadh",
    image: "",
    description: "The only place in the world with wild Asiatic lions roaming free in their natural habitat.",
    bestTime: "December - March",
    entryFee: 200,
    rating: 4.7,
    location: "Junagadh, Gujarat",
  },
  {
    name: "Somnath Temple",
    state: "Gujarat",
    city: "Gir Somnath",
    image: "",
    description: "One of the twelve Jyotirlinga shrines of Lord Shiva, situated on the shores of the Arabian Sea.",
    bestTime: "October - March",
    entryFee: 0,
    rating: 4.7,
    location: "Gir Somnath, Gujarat",
  },
  {
    name: "Sabarmati Ashram",
    state: "Gujarat",
    city: "Ahmedabad",
    image: "",
    description: "Former residence of Mahatma Gandhi on the banks of the Sabarmati river, now a museum and memorial.",
    bestTime: "October - March",
    entryFee: 0,
    rating: 4.6,
    location: "Ahmedabad, Gujarat",
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB Atlas");

    await Place.deleteMany({});
    console.log("Cleared existing places");

    const inserted = await Place.insertMany(places);
    console.log(`Inserted ${inserted.length} places (${places.length / 10} per state x 10 states)`);

    await mongoose.disconnect();
    console.log("Done. Disconnected.");
  } catch (err) {
    console.error("Seeding failed:", err);
    process.exit(1);
  }
}

seedDatabase();
